### ISSUE TITLE
replace toblerone in logo

### ISSUE THREAD

**Issue by AJPfleger** [Georg-code/roeschti#8]
The toblerone chocolate bar in the logo might be out dated, as it probably stopped being a *Swiss* symbol.

## Sources

«Swiss made» ist nur, was wirklich in der Schweiz hergestellt wird. Weil Toblerone bald Teile seiner Produktion auslagert, muss die Schokolade anders benannt und bebildert werden.

https://www.nzz.ch/wissenschaft/toblerone-produziert-kuenftig-in-der-slowakei-und-muss-deshalb-seine-schweizer-herkunft-abschwaechen-darunter-leidet-das-matterhorn-ld.1728797

Weil die Produktion von der Schweiz in die Slowakei verlegt wird, geht der dreieckigen Schokolade die "Swissness" verloren

https://www.derstandard.at/story/2000144231473/abgeknackt-das-matterhorn-muss-von-der-toblerone-verpackung-verschwinden

Switzerland’s iconic Matterhorn mountain, sometimes called the “Toblerone mountain”, is to disappear from the packaging of the famous Swiss chocolate bar, as it is also being made abroad.

https://www.swissinfo.ch/eng/business/matterhorn-to-disappear-from-toblerone-chocolate-bars/48330818

Rules about "Swissness" dictate some products cannot use national symbols if not exclusively made in the country

https://www.bbc.com/news/business-64854720

## Possible Solutions
Thinking of other Swiss symbols to add:
- Watches: They are famously Swiss, but I think most of them originate from the Geneva area, which is not connected to *Schwitzerdütsch*.
- Swiss Army Knife: Victorinox is from the canton Schwyz, which speaks *dütsch*. Also it symbolises how powerfull *roeschti* is as a language.

**Comment by Georg-code** [comment]
Hey! Thank you very much for pointing this out! I updated the logo and added the swiss symbols you suggested.
